import type { DailyActivitySeedDef } from "./daily-activity-seed-types";

/**
 * Operational simplification layer.
 *
 * Keep old template rows for history, but stop assigning overly-fragmented
 * templates to staff after the admin runs Seed/Sync Template Kegiatan.
 */
export const DEPRECATED_DAILY_ACTIVITY_TEMPLATE_CODES = [
  "RTPL-PA01",
  "RTPL-PA02",
  "RTPL-PA03",
  "RTPL-PA04",
  "RTPL-PA05",
  "RTPL-PA06",
  "RTPL-PA07",
  "RTPL-PA08",
  "RTPL-SPA01",
  "RTPL-SPA02",
  "RTPL-SPA03",
  "RTPL-SPA04",
  "RTPL-SPA05",
  "RTPL-SPA06",
  "RTPL-SPA07",
  "RTPL-MKB01",
  "RTPL-MKB02",
  "RTPL-MKB03",
  "RTPL-MKB04",
  "RTPL-MKB05",
  "RTPL-MKB06",
  "RTPL-MKB07",
  "RTPL-MKB08",
  "RTPL-LDR01",
  "RTPL-LDR02",
  "RTPL-LDR03",
  "RTPL-LDR04",
  "RTPL-LDR05",
  "RTPL-LDR06",
  "RTPL-LDR07",
  "RTPL-LDR08",
  "RTPL-MFB01",
  "RTPL-MFB02",
  "RTPL-MFB03",
  "RTPL-MFB04",
  "RTPL-MFB05",
  "RTPL-MFB06",
  "RTPL-MFB07",
  "RTPL-MNF01",
  "RTPL-MNF02",
  "RTPL-MNF03",
  "RTPL-MNF04",
  "RTPL-MNF05",
  "RTPL-MNF06",
  "RTPL-MNF07",
] as const;

export const DAILY_ACTIVITY_OPERATIONAL_OVERRIDES: DailyActivitySeedDef[] = [
  // Kasir: opening dan closing tidak boleh dicampur dalam satu jam target.
  {
    code: "RTPL-KSR01",
    title: "Opening Kas Harian",
    category: "Opening",
    position_group: "Kasir",
    standard_result:
      "Kas siap operasional: modal awal tercatat, perangkat pembayaran aktif, uang kecil siap, dan area kas rapi.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "08:00",
    target_time_end: "09:00",
    sort_order: 1,
    checklist: [
      "Modal awal kas sudah dihitung dan dicatat",
      "POS / mesin kas / printer struk berfungsi",
      "EDC / QRIS siap digunakan",
      "Kertas struk dan alat tulis tersedia",
      "Uang kecil / float tersedia sesuai kebutuhan",
      "Closing hari sebelumnya tidak menyisakan selisih tanpa penjelasan",
      "Area kas bersih dan rapi",
    ],
  },
  {
    code: "RTPL-KSR02",
    title: "Closing & Rekonsiliasi Kas Harian",
    category: "Closing",
    position_group: "Kasir",
    standard_result:
      "Semua transaksi hari ini selesai direkonsiliasi, selisih dijelaskan, dan kas aman diserahterimakan.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "21:00",
    target_time_end: "22:00",
    sort_order: 2,
    checklist: [
      "Pastikan seluruh transaksi sudah settle / tercatat",
      "Cocokkan tunai dengan laporan POS",
      "Cocokkan EDC / QRIS / transfer dengan laporan",
      "Cek void, refund, diskon manual, complimentary, atau transaksi khusus",
      "Selisih wajib ditulis nominal dan penyebabnya",
      "Kas / dokumen closing diserahkan atau diamankan sesuai SOP",
      "Kirim ringkasan closing kepada leader",
    ],
  },

  // PA / OB: hasil kerja dibagi empat blok, bukan delapan kartu dengan bobot sama.
  {
    code: "RTPL-PA11",
    title: "Opening Kebersihan & Toilet Customer",
    category: "Opening",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Sebelum ramai, area customer dan toilet sudah bersih, kering, tidak bau, rapi, dan layak menerima tamu.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "08:30",
    target_time_end: "10:00",
    sort_order: 1,
    checklist: [
      "Area depan, jalur masuk, meja, kursi, dan lantai sudah bersih",
      "Kolong meja tidak menyimpan sampah",
      "Toilet: kloset, lantai, wastafel, dan kaca sudah dibersihkan",
      "Toilet tidak bau dan lantai tidak licin / becek",
      "Sabun, tisu, dan perlengkapan toilet tersedia",
      "Tempat sampah customer dan toilet tidak penuh / bau",
      "Area tunggu / sekitar kasir terlihat rapi",
      "Foto menampilkan kondisi akhir area secara luas",
    ],
  },
  {
    code: "RTPL-PA12",
    title: "Jaga Area Customer, Toilet & Sampah Tetap Siap",
    category: "Cleaning",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Selama operasional, meja cepat di-reset, lantai tidak dibiarkan kotor, toilet terpantau, dan sampah tidak menumpuk.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "20:30",
    sort_order: 2,
    checklist: [
      "Meja bekas customer dibersihkan dan kursi dirapikan",
      "Lantai / kolong meja dicek dari remah, tisu, tulang, atau sampah kecil",
      "Area kotor tidak dibiarkan lebih dari 5 menit jika kondisi memungkinkan",
      "Toilet dicek berkala; bau / kotor / perlengkapan habis langsung ditangani atau dilapor",
      "Tempat sampah customer, toilet, dan outdoor tidak penuh atau meluber",
      "Mushola / area ibadah tetap bersih dan rapi jika tersedia",
      "Jika kondisi ramai menghambat pekerjaan, tulis kendala secara jelas",
      "Foto menunjukkan kondisi area setelah dirapikan",
    ],
  },
  {
    code: "RTPL-PA13",
    title: "Rapikan Outdoor, Parkiran & Tanaman",
    category: "Maintenance",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Area depan memberi kesan rapi: parkiran bersih, akses aman, tanaman terawat, dan sampah outdoor terkendali.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "15:00",
    target_time_end: "16:30",
    sort_order: 3,
    checklist: [
      "Parkiran dan jalur masuk bersih dari daun, plastik, tisu, dan puntung rokok",
      "Tidak ada genangan / area licin yang dibiarkan tanpa laporan",
      "Tanaman dicek dan disiram sesuai kondisi cuaca",
      "Daun kering dan sampah dalam pot dibersihkan",
      "Rumput liar kecil di jalur customer dirapikan",
      "Selang / alat siram dikembalikan ke tempatnya",
      "Tanaman rusak / kering difoto dan dilaporkan",
    ],
  },
  {
    code: "RTPL-PA14",
    title: "Closing Public Area",
    category: "Closing",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Outlet ditinggal dalam kondisi area customer bersih, toilet aman, sampah terkendali, dan tidak mewariskan kotoran ke shift berikutnya.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "21:00",
    target_time_end: "22:00",
    sort_order: 4,
    checklist: [
      "Meja dan kursi sudah bersih serta rapi",
      "Lantai dan kolong meja dicek ulang",
      "Toilet closing dicek ulang",
      "Tempat sampah penuh / bau sudah dibuang",
      "Area depan tidak menyisakan sampah malam",
      "Peralatan kebersihan dicuci dan dikembalikan ke tempatnya",
      "Kendala closing ditulis jelas",
      "Foto menunjukkan kondisi akhir area",
    ],
  },

  // Leader: Daily Activity = fungsi manajerial. Audit fisik tetap di Leader Monitoring.
  {
    code: "RTPL-LDR11",
    title: "Start Shift: Tim & Prioritas Hari Ini",
    category: "Opening",
    position_group: "LeaderOutlet",
    standard_result:
      "Sebelum operasional, manpower, PIC area, target, promo, stok kritis, dan pekerjaan khusus sudah jelas ke tim.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "07:30",
    target_time_end: "08:30",
    sort_order: 1,
    checklist: [
      "Cek hadir, telat, izin, dan kekosongan manpower",
      "Tentukan PIC setiap area / posisi penting",
      "Sampaikan target, promo, reservasi, atau kunjungan hari ini",
      "Sampaikan menu kosong / stok kritis yang sudah diketahui",
      "Tentukan maksimal 3 prioritas operasional hari ini",
      "Pastikan tim tahu siapa yang harus dihubungi jika ada kendala",
    ],
  },
  {
    code: "RTPL-LDR12",
    title: "Kendali Bisnis & Tindak Lanjut Operasional",
    category: "Monitoring",
    position_group: "LeaderOutlet",
    standard_result:
      "Leader mengambil keputusan atas stok kritis, antrean, komplain, transaksi khusus, dan kendala staf; bukan sekadar mengulang audit fisik.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "09:30",
    target_time_end: "18:00",
    sort_order: 2,
    checklist: [
      "Stok kritis / menu kosong sudah diberi keputusan atau alternatif",
      "Antrean / waktu tunggu abnormal sudah ditangani",
      "Komplain customer yang perlu eskalasi sudah diselesaikan / diberi PIC",
      "Void, refund, diskon manual, complimentary, atau transaksi khusus diperiksa",
      "Kendala staff sudah diberi PIC, deadline, dan status follow up",
      "Masalah yang butuh owner / admin sudah dieskalasikan, bukan ditunda tanpa status",
    ],
  },
  {
    code: "RTPL-LDR13",
    title: "Closing, Selisih & Eskalasi Outlet",
    category: "Closing",
    position_group: "LeaderOutlet",
    standard_result:
      "Sebelum selesai shift, status tiap divisi, transaksi, kendala terbuka, dan prioritas besok sudah jelas serta terlapor.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "21:00",
    target_time_end: "22:00",
    sort_order: 3,
    checklist: [
      "Pastikan closing kasir, dapur, bar, dan public area sudah berstatus selesai / ada kendala",
      "Cek selisih atau transaksi khusus yang belum memiliki penjelasan",
      "Catat masalah operasional yang masih open dan PIC-nya",
      "Catat pekerjaan yang harus dilanjutkan besok",
      "Eskalasi isu penting ke owner / admin dengan konteks dan keputusan yang dibutuhkan",
      "Kirim ringkasan outlet; audit fisik closing tetap dilakukan lewat Leader Monitoring",
    ],
  },

  // Supir / PA: tiga blok kerja, detail perjalanan tetap dicatat di checklist/catatan.
  {
    code: "RTPL-SPA11",
    title: "Kendaraan & Agenda Siap Jalan",
    category: "Opening",
    position_group: "SupirPA",
    standard_result:
      "Kendaraan aman dan agenda/rute hari ini sudah jelas sebelum perjalanan dimulai.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "07:00",
    target_time_end: "08:00",
    sort_order: 1,
    checklist: [
      "Cek BBM, ban, lampu, rem, indikator, dan kebersihan kendaraan",
      "Laporkan kerusakan yang memengaruhi keselamatan / perjalanan",
      "Cek agenda, titik jemput, tujuan, dan urutan perjalanan",
      "Konfirmasi barang / dokumen yang harus dibawa",
      "Foto kondisi kendaraan sebelum dipakai",
    ],
  },
  {
    code: "RTPL-SPA12",
    title: "Perjalanan, Pengantaran & Pembelian Hari Ini",
    category: "Delivery",
    position_group: "SupirPA",
    standard_result:
      "Perjalanan, pengantaran, pengambilan, dan pembelian selesai tepat tujuan dengan bukti serta kendala tercatat.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "08:00",
    target_time_end: "17:00",
    sort_order: 2,
    checklist: [
      "Pastikan penerima, tujuan, barang, dan jumlah benar",
      "Untuk pembelian, cek spesifikasi, jumlah, kualitas, dan harga",
      "Simpan nota / bukti serah terima",
      "Catat perjalanan / tugas yang selesai",
      "Laporkan keterlambatan, perubahan rute, atau tugas yang belum selesai",
      "Serahkan barang / dokumen kepada PIC yang benar",
    ],
  },
  {
    code: "RTPL-SPA13",
    title: "Pengeluaran & Closing Kendaraan",
    category: "Closing",
    position_group: "SupirPA",
    standard_result:
      "Pengeluaran perjalanan lengkap buktinya, kendaraan rapi, dan agenda tertunda / besok sudah diketahui.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "17:00",
    target_time_end: "18:00",
    sort_order: 3,
    checklist: [
      "Catat BBM, tol, parkir, dan pengeluaran perjalanan lain",
      "Foto / simpan seluruh nota yang wajib dipertanggungjawabkan",
      "Rapikan kabin dan bagasi; cek barang tertinggal",
      "Catat perjalanan yang tertunda dan alasannya",
      "Cek kebutuhan perjalanan besok",
      "Foto kondisi akhir kendaraan",
    ],
  },

  // Maintenance & kebun: safety -> work order -> closing safety/routine.
  {
    code: "RTPL-MKB11",
    title: "Inspeksi Safety & Kerusakan Prioritas",
    category: "Maintenance",
    position_group: "MaintenanceKebon",
    standard_result:
      "Risiko listrik, air, akses, fasilitas rusak, dan kerusakan yang mengganggu operasional ditemukan sebelum menjadi masalah besar.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "07:30",
    target_time_end: "09:30",
    sort_order: 1,
    checklist: [
      "Cek pintu, kunci, engsel, meja, kursi, lantai, dinding, dan plafon yang bermasalah",
      "Cek lampu, kabel, stop kontak, dan sakelar berbahaya",
      "Cek aliran air, kebocoran, pompa, toilet, dan saluran",
      "Tandai temuan: aman / perlu perbaikan / darurat",
      "Amankan titik berbahaya yang tidak boleh dipakai",
      "Foto temuan dan tentukan prioritas penanganan",
    ],
  },
  {
    code: "RTPL-MKB12",
    title: "Perbaikan & Work Order Fasilitas",
    category: "Maintenance",
    position_group: "MaintenanceKebon",
    standard_result:
      "Perbaikan prioritas dikerjakan sampai diuji; pekerjaan yang tidak bisa ditangani memiliki eskalasi, kebutuhan bahan, dan status jelas.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "09:30",
    target_time_end: "17:00",
    sort_order: 2,
    checklist: [
      "Pilih pekerjaan berdasarkan dampak dan urgensi, bukan yang paling mudah",
      "Siapkan alat / bahan sebelum mulai",
      "Foto sebelum perbaikan untuk pekerjaan fisik",
      "Kerjakan dan uji kembali fungsi setelah perbaikan",
      "Bersihkan area kerja setelah selesai",
      "Jika butuh teknisi / spare part / pembelian, tulis kebutuhan dan deadline",
      "Update status: selesai / on progress / menunggu pihak lain",
    ],
  },
  {
    code: "RTPL-MKB13",
    title: "Kebun, Alat & Closing Keamanan",
    category: "Closing",
    position_group: "MaintenanceKebon",
    standard_result:
      "Area hijau terawat, alat kerja rapi, dan sebelum tutup tidak ada risiko listrik, air, akses, atau alat maintenance yang tertinggal.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "15:00",
    target_time_end: "21:30",
    sort_order: 3,
    checklist: [
      "Siram / rawat tanaman sesuai kebutuhan dan rapikan daun / rumput yang mengganggu",
      "Rapikan alat kerja serta catat spare part yang hampir habis",
      "Cek titik listrik dan alat yang harus dimatikan",
      "Cek keran, pompa, dan potensi kebocoran",
      "Cek pintu / akses fasilitas yang menjadi tanggung jawab maintenance",
      "Foto kondisi akhir area penting dan laporkan risiko yang belum selesai",
    ],
  },

  // Marketing FnB: prioritas -> eksekusi -> hasil, bukan tujuh laporan kecil.
  {
    code: "RTPL-MFB11",
    title: "Prioritas Marketing FnB Hari Ini",
    category: "Marketing",
    position_group: "MarketingFnB",
    standard_result:
      "Hari dimulai dengan maksimal tiga prioritas yang jelas berdasarkan kalender konten, campaign, stok/menu, KOL, dan kebutuhan outlet.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "09:00",
    target_time_end: "10:00",
    sort_order: 1,
    checklist: [
      "Cek kalender konten Buri Umah, Kisamen, dan Samtaro",
      "Cek campaign / promo / menu baru yang sedang aktif",
      "Cek material, outlet, atau produk yang berpotensi menghambat eksekusi",
      "Cek KOL / creator yang memiliki deadline hari ini",
      "Tentukan maksimal 3 prioritas berdasarkan dampak ke penjualan / deadline",
      "Sampaikan kebutuhan yang harus dibantu divisi lain",
    ],
  },
  {
    code: "RTPL-MFB12",
    title: "Eksekusi Konten, KOL & Campaign FnB",
    category: "Marketing",
    position_group: "MarketingFnB",
    standard_result:
      "Prioritas marketing bergerak menjadi output nyata: brief, produksi, KOL, publikasi, atau koordinasi campaign memiliki status jelas.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "16:00",
    sort_order: 2,
    checklist: [
      "Brief konten memiliki tujuan, hook, menu, shot list, dan CTA",
      "Jadwal talent / shooting / produk / lokasi sudah dikonfirmasi jika dibutuhkan",
      "KOL / barter yang aktif sudah di-follow up sampai next action jelas",
      "Konten yang harus tayang sudah dicek caption, tag, dan kualitasnya",
      "Campaign aktif dicek kesesuaian materi, periode, dan kebutuhan outlet",
      "Pekerjaan tertunda memiliki alasan dan next action, bukan hanya status pending",
    ],
  },
  {
    code: "RTPL-MFB13",
    title: "Hasil Marketing FnB & Prioritas Besok",
    category: "Closing",
    position_group: "MarketingFnB",
    standard_result:
      "Output hari ini, hasil awal, kendala, dan prioritas besok tercatat singkat agar owner melihat progres, bukan daftar aktivitas.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "16:00",
    target_time_end: "17:00",
    sort_order: 3,
    checklist: [
      "Catat output yang benar-benar selesai / tayang hari ini",
      "Catat respons awal penting: views, komentar, pertanyaan, atau masalah",
      "Catat progres KOL / creator dan next action",
      "Catat campaign / pekerjaan yang tertunda beserta penyebabnya",
      "Tentukan maksimal 3 prioritas besok",
      "Eskalasi keputusan yang dibutuhkan dari owner",
    ],
  },

  // Marketing NF: fokus produk -> eksekusi -> hasil.
  {
    code: "RTPL-MNF11",
    title: "Prioritas Produk & Marketing NF Hari Ini",
    category: "Marketing",
    position_group: "MarketingNF",
    standard_result:
      "Produk, stok, audience, campaign, dan target hari ini sudah dipilih sehingga tim tidak membuat konten tanpa prioritas penjualan.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "08:30",
    target_time_end: "10:00",
    sort_order: 1,
    checklist: [
      "Cek stok produk utama, slow moving, dead stock, produk baru, dan produk promo",
      "Cek kalender konten serta campaign marketplace / ads yang aktif",
      "Cek pertanyaan / komplain berulang dari CS sebagai bahan prioritas",
      "Tentukan produk dan audience utama hari ini",
      "Tentukan maksimal 3 prioritas berdasarkan dampak penjualan / deadline",
      "Koordinasikan mismatch stok, harga, voucher, atau campaign ke PIC terkait",
    ],
  },
  {
    code: "RTPL-MNF12",
    title: "Eksekusi Konten, Affiliate & Campaign NF",
    category: "Marketing",
    position_group: "MarketingNF",
    standard_result:
      "Prioritas NF berubah menjadi output: brief edukasi/penjualan, konten, affiliate/KOL, dan koordinasi campaign memiliki next action jelas.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "16:00",
    sort_order: 2,
    checklist: [
      "Brief menyebut masalah customer, manfaat, cara pakai, bukti, hook, dan CTA",
      "Konten / shooting / editing prioritas hari ini bergerak sesuai deadline",
      "Creator / affiliate / KOL yang aktif sudah di-follow up",
      "Permintaan sampel / pengiriman produk memiliki PIC dan status",
      "Campaign marketplace / iklan dicek dari sisi produk, stok, harga, dan materi",
      "Feedback CS yang penting diterjemahkan menjadi FAQ / materi edukasi / perbaikan brief",
    ],
  },
  {
    code: "RTPL-MNF13",
    title: "Hasil Marketing NF & Prioritas Besok",
    category: "Closing",
    position_group: "MarketingNF",
    standard_result:
      "Output konten, progres affiliate, campaign, feedback customer, kendala, dan prioritas besok tercatat singkat dan bisa ditindaklanjuti.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "16:00",
    target_time_end: "17:00",
    sort_order: 3,
    checklist: [
      "Catat output yang selesai / tayang hari ini",
      "Catat progres affiliate / KOL / sampel dan next action",
      "Catat feedback customer yang perlu ditindaklanjuti",
      "Catat campaign atau pekerjaan yang tertunda beserta penyebabnya",
      "Tentukan maksimal 3 prioritas besok",
      "Eskalasi keputusan yang dibutuhkan dari owner",
    ],
  },
];
