/**
 * Extended daily activity templates — 5 posisi baru (37 kegiatan).
 * Idempotent via stable `code` keys. Merge ke DAILY_ACTIVITY_SEED_TEMPLATES.
 */
import type { DailyActivitySeedDef } from "./daily-activity-seed-types";

export const DAILY_ACTIVITY_EXTENDED_TEMPLATES: DailyActivitySeedDef[] = [
  // ═══ Supir / Personal Assistant (7) ═══
  {
    code: "RTPL-SPA01",
    title: "Cek Kendaraan Sebelum Digunakan",
    category: "Maintenance",
    position_group: "SupirPA",
    standard_result:
      "Kendaraan siap dipakai, aman, bersih, bahan bakar cukup, dan tidak ada kerusakan yang mengganggu perjalanan.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "07:00",
    target_time_end: "07:30",
    sort_order: 1,
    checklist: [
      "Cek bahan bakar",
      "Cek tekanan dan kondisi ban",
      "Cek lampu, rem, dan indikator kendaraan",
      "Cek kebersihan bagian dalam kendaraan",
      "Foto kondisi kendaraan",
      "Laporkan kerusakan jika ditemukan",
    ],
  },
  {
    code: "RTPL-SPA02",
    title: "Konfirmasi Agenda dan Rute Harian",
    category: "General",
    position_group: "SupirPA",
    standard_result:
      "Agenda perjalanan, penjemputan, pengantaran, pembelian, dan kebutuhan owner sudah diketahui sebelum berangkat.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "07:30",
    target_time_end: "08:00",
    sort_order: 2,
    checklist: [
      "Cek agenda hari ini",
      "Konfirmasi titik jemput dan tujuan",
      "Susun urutan perjalanan",
      "Cek estimasi waktu perjalanan",
      "Konfirmasi barang atau dokumen yang harus dibawa",
    ],
  },
  {
    code: "RTPL-SPA03",
    title: "Antar Jemput dan Pengiriman",
    category: "Delivery",
    position_group: "SupirPA",
    standard_result:
      "Penjemputan, pengantaran orang, dokumen, bahan, produk, atau perlengkapan dilakukan tepat tujuan dan tercatat.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "08:00",
    target_time_end: "17:00",
    sort_order: 3,
    checklist: [
      "Pastikan penerima dan lokasi benar",
      "Cek barang sebelum dibawa",
      "Pastikan barang diterima tujuan",
      "Ambil foto atau bukti serah terima",
      "Catat perjalanan yang selesai",
      "Laporkan keterlambatan atau kendala",
    ],
  },
  {
    code: "RTPL-SPA04",
    title: "Pembelian dan Pengambilan Keperluan",
    category: "Purchasing",
    position_group: "SupirPA",
    standard_result:
      "Barang yang ditugaskan dibeli atau diambil sesuai nama, jumlah, kualitas, harga, dan lokasi yang disepakati.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "09:00",
    target_time_end: "15:00",
    sort_order: 4,
    checklist: [
      "Cek daftar barang",
      "Konfirmasi spesifikasi barang",
      "Cek jumlah barang saat diterima",
      "Simpan nota atau struk",
      "Foto barang yang dibeli",
      "Serahkan barang kepada PIC terkait",
    ],
  },
  {
    code: "RTPL-SPA05",
    title: "Catat BBM, Tol, Parkir, dan Pengeluaran",
    category: "Administration",
    position_group: "SupirPA",
    standard_result:
      "Semua pengeluaran perjalanan tercatat dan memiliki bukti yang dapat diperiksa Finance.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "16:00",
    target_time_end: "17:00",
    sort_order: 5,
    checklist: [
      "Catat pembelian BBM",
      "Catat biaya tol",
      "Catat biaya parkir",
      "Foto seluruh nota",
      "Tulis perjalanan terkait",
      "Serahkan atau unggah bukti pengeluaran",
    ],
  },
  {
    code: "RTPL-SPA06",
    title: "Rapikan Kendaraan dan Barang Bawaan",
    category: "Cleaning",
    position_group: "SupirPA",
    standard_result:
      "Kendaraan kembali bersih, tidak ada barang tertinggal, dan siap digunakan kembali.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "17:00",
    target_time_end: "17:30",
    sort_order: 6,
    checklist: [
      "Buang sampah kendaraan",
      "Cek barang tertinggal",
      "Rapikan kabin",
      "Rapikan bagasi",
      "Foto kondisi akhir kendaraan",
    ],
  },
  {
    code: "RTPL-SPA07",
    title: "Laporan Perjalanan dan Agenda Besok",
    category: "Closing",
    position_group: "SupirPA",
    standard_result:
      "Semua perjalanan hari ini tercatat dan kebutuhan perjalanan besok sudah diketahui.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "17:30",
    target_time_end: "18:00",
    sort_order: 7,
    checklist: [
      "Catat perjalanan yang selesai",
      "Catat perjalanan yang tertunda",
      "Catat kondisi kendaraan",
      "Catat pengeluaran hari ini",
      "Cek kebutuhan perjalanan besok",
      "Kirim laporan kepada owner atau PIC",
    ],
  },

  // ═══ Maintenance & Kebun (8) ═══
  {
    code: "RTPL-MKB01",
    title: "Inspeksi Kerusakan Area",
    category: "Maintenance",
    position_group: "MaintenanceKebon",
    standard_result:
      "Kerusakan fasilitas outlet diketahui lebih awal dan sudah ditentukan prioritas penanganannya.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "07:30",
    target_time_end: "08:30",
    sort_order: 1,
    checklist: [
      "Cek pintu, kunci, dan engsel",
      "Cek meja dan kursi yang rusak",
      "Cek plafon, dinding, dan lantai",
      "Cek keran dan saluran air",
      "Foto kerusakan yang ditemukan",
      "Tentukan status aman, perlu perbaikan, atau darurat",
    ],
  },
  {
    code: "RTPL-MKB02",
    title: "Cek Listrik, Lampu, dan Stop Kontak",
    category: "Maintenance",
    position_group: "MaintenanceKebon",
    standard_result:
      "Lampu, stop kontak, kabel, sakelar, dan perangkat listrik dalam kondisi aman.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "08:30",
    target_time_end: "09:30",
    sort_order: 2,
    checklist: [
      "Cek lampu mati",
      "Cek stop kontak longgar",
      "Cek kabel terkelupas",
      "Cek sakelar bermasalah",
      "Matikan titik yang berbahaya",
      "Laporkan kebutuhan teknisi jika tidak dapat ditangani",
    ],
  },
  {
    code: "RTPL-MKB03",
    title: "Cek Air, Pompa, Toilet, dan Saluran",
    category: "Maintenance",
    position_group: "MaintenanceKebon",
    standard_result:
      "Aliran air, pompa, toilet, wastafel, dan saluran pembuangan berfungsi normal tanpa kebocoran atau mampet.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "09:30",
    target_time_end: "10:30",
    sort_order: 3,
    checklist: [
      "Cek aliran air",
      "Cek kebocoran",
      "Cek pompa air",
      "Cek saluran mampet",
      "Cek bau dari saluran",
      "Foto titik yang bermasalah",
    ],
  },
  {
    code: "RTPL-MKB04",
    title: "Perbaikan Fasilitas Harian",
    category: "Maintenance",
    position_group: "MaintenanceKebon",
    standard_result:
      "Perbaikan ringan selesai ditangani dan perbaikan berat sudah dieskalasikan.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "10:30",
    target_time_end: "12:00",
    sort_order: 4,
    checklist: [
      "Pilih kerusakan prioritas",
      "Siapkan alat dan bahan",
      "Lakukan perbaikan",
      "Bersihkan area setelah perbaikan",
      "Foto sebelum dan sesudah",
      "Uji kembali fasilitas yang diperbaiki",
    ],
  },
  {
    code: "RTPL-MKB05",
    title: "Siram dan Rawat Tanaman",
    category: "Maintenance",
    position_group: "MaintenanceKebon",
    standard_result:
      "Tanaman hidup, tidak layu, pot bersih, dan area hijau terlihat rapi.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "15:00",
    target_time_end: "16:00",
    sort_order: 5,
    checklist: [
      "Siram tanaman sesuai kebutuhan",
      "Cek tanaman layu atau mati",
      "Bersihkan daun kering",
      "Bersihkan sampah dalam pot",
      "Cek kebutuhan pupuk",
      "Foto kondisi tanaman",
    ],
  },
  {
    code: "RTPL-MKB06",
    title: "Rapikan Kebun dan Rumput",
    category: "Cleaning",
    position_group: "MaintenanceKebon",
    standard_result:
      "Rumput liar, semak, daun kering, dan area kebun tidak terlihat berantakan.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "16:00",
    target_time_end: "17:00",
    sort_order: 6,
    checklist: [
      "Cabut rumput liar",
      "Rapikan tanaman yang menjalar",
      "Kumpulkan daun kering",
      "Rapikan batas taman",
      "Buang sampah kebun",
      "Foto hasil akhir",
    ],
  },
  {
    code: "RTPL-MKB07",
    title: "Cek Alat dan Spare Part Maintenance",
    category: "Stock",
    position_group: "MaintenanceKebon",
    standard_result:
      "Alat kerja dan spare part tersedia, tersimpan rapi, dan kekurangan sudah dicatat.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "17:00",
    target_time_end: "17:30",
    sort_order: 7,
    checklist: [
      "Cek alat kerja",
      "Cek kabel, lampu, keran, dan spare part",
      "Catat barang yang habis",
      "Rapikan tempat penyimpanan",
      "Ajukan kebutuhan pembelian",
    ],
  },
  {
    code: "RTPL-MKB08",
    title: "Closing Keamanan Fasilitas",
    category: "Closing",
    position_group: "MaintenanceKebon",
    standard_result:
      "Fasilitas outlet aman saat tutup dan tidak ada listrik, air, api, atau peralatan yang berisiko.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "20:30",
    target_time_end: "21:30",
    sort_order: 8,
    checklist: [
      "Cek titik listrik",
      "Cek keran air",
      "Cek pompa",
      "Cek pintu dan akses",
      "Cek alat maintenance tersimpan",
      "Foto kondisi akhir area penting",
    ],
  },

  // ═══ Leader Outlet (8) ═══
  {
    code: "RTPL-LDR01",
    title: "Cek Kehadiran dan Pembagian Tim",
    category: "Opening",
    position_group: "LeaderOutlet",
    standard_result:
      "Kehadiran staf diketahui dan setiap area memiliki penanggung jawab.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "07:30",
    target_time_end: "08:00",
    sort_order: 1,
    checklist: [
      "Cek staf hadir",
      "Cek staf terlambat",
      "Cek staf izin atau sakit",
      "Atur pengganti jika ada kekosongan",
      "Tentukan PIC setiap area",
      "Catat kekurangan tenaga kerja",
    ],
  },
  {
    code: "RTPL-LDR02",
    title: "Briefing Opening Outlet",
    category: "Opening",
    position_group: "LeaderOutlet",
    standard_result:
      "Tim mengetahui target, prioritas, promo, stok kosong, reservasi, dan pekerjaan khusus hari ini.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "08:00",
    target_time_end: "08:20",
    sort_order: 2,
    checklist: [
      "Sampaikan target hari ini",
      "Sampaikan promo aktif",
      "Sampaikan menu kosong atau terbatas",
      "Sampaikan reservasi atau kunjungan",
      "Sampaikan pekerjaan prioritas",
      "Foto briefing tim",
    ],
  },
  {
    code: "RTPL-LDR03",
    title: "Validasi Kesiapan Semua Area",
    category: "Monitoring",
    position_group: "LeaderOutlet",
    standard_result:
      "Kasir, bar, dapur, area customer, toilet, dan halaman benar-benar siap menerima customer.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "08:20",
    target_time_end: "09:30",
    sort_order: 3,
    checklist: [
      "Cek kasir",
      "Cek bar",
      "Cek dapur",
      "Cek area customer",
      "Cek toilet",
      "Cek halaman dan parkiran",
      "Foto titik yang belum sesuai",
    ],
  },
  {
    code: "RTPL-LDR04",
    title: "Cek Stok Kritis dan Menu Kosong",
    category: "Stock",
    position_group: "LeaderOutlet",
    standard_result:
      "Stok kritis, menu kosong, bahan terlambat, dan kebutuhan pembelian diketahui sebelum mengganggu penjualan.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "09:30",
    target_time_end: "10:30",
    sort_order: 4,
    checklist: [
      "Cek laporan dapur dan bar",
      "Cek stok kritis",
      "Cek menu berstatus habis",
      "Konfirmasi kebutuhan purchasing",
      "Tentukan alternatif penjualan",
      "Informasikan ke kasir dan waiter",
    ],
  },
  {
    code: "RTPL-LDR05",
    title: "Kontrol Pelayanan dan Kondisi Outlet",
    category: "Monitoring",
    position_group: "LeaderOutlet",
    standard_result:
      "Pelayanan customer, waktu tunggu, kebersihan, dan disiplin staf tetap terkontrol selama operasional.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "11:00",
    target_time_end: "15:00",
    sort_order: 5,
    checklist: [
      "Cek waktu tunggu pesanan",
      "Cek antrean kasir",
      "Cek kebersihan meja",
      "Cek staf berada di area kerja",
      "Cek komplain customer",
      "Tegur atau arahkan staf jika ditemukan masalah",
    ],
  },
  {
    code: "RTPL-LDR06",
    title: "Cek Transaksi Khusus dan Selisih",
    category: "Finance",
    position_group: "LeaderOutlet",
    standard_result:
      "Void, refund, diskon, complimentary, marketing cost, dan selisih transaksi diketahui leader.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "15:00",
    target_time_end: "16:00",
    sort_order: 6,
    checklist: [
      "Cek transaksi void",
      "Cek transaksi refund",
      "Cek diskon manual",
      "Cek complimentary",
      "Cek transaksi biaya marketing",
      "Catat transaksi yang perlu pemeriksaan owner",
    ],
  },
  {
    code: "RTPL-LDR07",
    title: "Tindak Lanjut Kendala Operasional",
    category: "Kendala",
    position_group: "LeaderOutlet",
    standard_result:
      "Kendala dari staf sudah dibaca, diberikan PIC, dan memiliki status tindak lanjut.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "16:00",
    target_time_end: "18:00",
    sort_order: 7,
    checklist: [
      "Buka daftar kendala",
      "Tentukan tingkat prioritas",
      "Tentukan PIC penanganan",
      "Berikan instruksi tindak lanjut",
      "Ubah status kendala",
      "Eskalasi ke owner jika diperlukan",
    ],
  },
  {
    code: "RTPL-LDR08",
    title: "Closing dan Laporan Outlet",
    category: "Closing",
    position_group: "LeaderOutlet",
    standard_result:
      "Outlet ditutup aman, pekerjaan divisi diperiksa, transaksi selesai, dan laporan harian terkirim.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "21:00",
    target_time_end: "22:00",
    sort_order: 8,
    checklist: [
      "Cek closing kasir",
      "Cek closing dapur",
      "Cek closing bar",
      "Cek area customer",
      "Cek keamanan listrik dan air",
      "Catat omzet atau transaksi hari ini",
      "Catat masalah dan pekerjaan tertunda",
      "Kirim laporan outlet",
    ],
  },

  // ═══ Marketing FnB (7) ═══
  {
    code: "RTPL-MFB01",
    title: "Cek Kalender Konten FnB",
    category: "Marketing",
    position_group: "MarketingFnB",
    standard_result:
      "Jadwal konten seluruh brand FnB hari ini diketahui dan tidak ada konten yang terlewat.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "09:00",
    target_time_end: "09:30",
    sort_order: 1,
    checklist: [
      "Cek konten Buri Umah",
      "Cek konten Kisamen",
      "Cek konten Samtaro",
      "Cek status draft, edit, approval, atau tayang",
      "Tandai konten yang terlambat",
      "Tentukan prioritas hari ini",
    ],
  },
  {
    code: "RTPL-MFB02",
    title: "Cek Promo dan Campaign Aktif",
    category: "Marketing",
    position_group: "MarketingFnB",
    standard_result:
      "Promo, campaign, menu baru, KOL, dan aktivasi outlet berjalan sesuai periode dan target.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "09:30",
    target_time_end: "10:30",
    sort_order: 2,
    checklist: [
      "Cek campaign aktif",
      "Cek tanggal mulai dan selesai",
      "Cek menu yang dipromosikan",
      "Cek material yang belum siap",
      "Cek kebutuhan outlet",
      "Catat kendala campaign",
    ],
  },
  {
    code: "RTPL-MFB03",
    title: "Siapkan Brief Konten Harian",
    category: "Marketing",
    position_group: "MarketingFnB",
    standard_result:
      "Konten yang akan dibuat memiliki tujuan, hook, menu utama, shot list, caption direction, dan CTA yang jelas.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "10:30",
    target_time_end: "12:00",
    sort_order: 3,
    checklist: [
      "Tentukan brand",
      "Tentukan menu atau program",
      "Tentukan tujuan konten",
      "Tulis hook",
      "Tulis shot list",
      "Tulis CTA",
      "Kirim brief kepada talent, videografer, atau editor",
    ],
  },
  {
    code: "RTPL-MFB04",
    title: "Koordinasi Produksi Konten",
    category: "General",
    position_group: "MarketingFnB",
    standard_result:
      "Jadwal syuting, talent, produk, lokasi, dan kebutuhan produksi sudah dikonfirmasi.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "12:00",
    target_time_end: "14:00",
    sort_order: 4,
    checklist: [
      "Konfirmasi jadwal syuting",
      "Konfirmasi talent",
      "Konfirmasi menu",
      "Konfirmasi lokasi",
      "Konfirmasi PIC outlet",
      "Pastikan bahan atau produk tersedia",
    ],
  },
  {
    code: "RTPL-MFB05",
    title: "Follow Up KOL dan Barter FnB",
    category: "Marketing",
    position_group: "MarketingFnB",
    standard_result:
      "KOL yang sedang diproses memiliki status jelas dari kontak, deal, visit, posting, sampai evaluasi.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "14:00",
    target_time_end: "15:30",
    sort_order: 5,
    checklist: [
      "Cek KOL yang belum membalas",
      "Cek KOL yang sudah deal",
      "Konfirmasi tanggal kunjungan",
      "Konfirmasi menu complimentary",
      "Informasikan PIC outlet",
      "Cek batas waktu posting",
      "Update status di Campaign OS",
    ],
  },
  {
    code: "RTPL-MFB06",
    title: "Cek Konten Tayang dan Respons Audience",
    category: "Monitoring",
    position_group: "MarketingFnB",
    standard_result:
      "Konten yang tayang sudah diperiksa kualitasnya dan respons awal audience tercatat.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "15:30",
    target_time_end: "16:30",
    sort_order: 6,
    checklist: [
      "Cek konten sudah tayang",
      "Cek caption dan tag",
      "Cek kualitas video atau foto",
      "Catat views awal",
      "Catat komentar penting",
      "Catat pertanyaan customer",
      "Laporkan kesalahan konten",
    ],
  },
  {
    code: "RTPL-MFB07",
    title: "Laporan Marketing FnB Harian",
    category: "Closing",
    position_group: "MarketingFnB",
    standard_result:
      "Aktivitas konten, campaign, KOL, kendala, dan pekerjaan besok tercatat.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "16:30",
    target_time_end: "17:00",
    sort_order: 7,
    checklist: [
      "Catat konten yang tayang",
      "Catat konten yang belum selesai",
      "Catat progres KOL",
      "Catat campaign aktif",
      "Catat kendala outlet",
      "Tulis prioritas besok",
      "Kirim laporan ke owner",
    ],
  },

  // ═══ Marketing NF (7) ═══
  {
    code: "RTPL-MNF01",
    title: "Cek Kalender Konten NF",
    category: "Marketing",
    position_group: "MarketingNF",
    standard_result:
      "Konten produk NF hari ini memiliki produk, target audience, format, dan status produksi yang jelas.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "08:30",
    target_time_end: "09:00",
    sort_order: 1,
    checklist: [
      "Cek produk yang dipromosikan",
      "Cek target ikan atau kebutuhan pemancing",
      "Cek format video atau foto",
      "Cek status script",
      "Cek status shooting dan editing",
      "Tandai konten yang terlambat",
    ],
  },
  {
    code: "RTPL-MNF02",
    title: "Cek Produk, Stok, dan Prioritas Penjualan",
    category: "Stock",
    position_group: "MarketingNF",
    standard_result:
      "Produk yang dipromosikan sesuai kondisi stok dan target penjualan.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "09:00",
    target_time_end: "10:00",
    sort_order: 2,
    checklist: [
      "Cek stok produk utama",
      "Cek produk slow moving",
      "Cek produk dead stock",
      "Cek produk baru",
      "Cek produk yang sedang promo",
      "Tentukan produk prioritas hari ini",
    ],
  },
  {
    code: "RTPL-MNF03",
    title: "Siapkan Brief Konten Produk NF",
    category: "Marketing",
    position_group: "MarketingNF",
    standard_result:
      "Konten NF memiliki masalah customer, solusi produk, cara pakai, bukti, hook, dan CTA yang jelas.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "11:30",
    sort_order: 3,
    checklist: [
      "Tentukan produk",
      "Tentukan target ikan",
      "Tentukan masalah customer",
      "Tulis manfaat utama",
      "Tulis cara pakai",
      "Tulis hook",
      "Tulis CTA",
      "Kirim brief ke talent atau editor",
    ],
  },
  {
    code: "RTPL-MNF04",
    title: "Koordinasi Konten, Affiliate, dan KOL NF",
    category: "Marketing",
    position_group: "MarketingNF",
    standard_result:
      "Konten affiliate, creator, KOL, dan akun internal NF memiliki status yang jelas.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "11:30",
    target_time_end: "13:00",
    sort_order: 4,
    checklist: [
      "Cek creator yang aktif",
      "Cek permintaan sampel",
      "Cek produk yang akan dikirim",
      "Cek tanggal upload",
      "Cek kode affiliate jika tersedia",
      "Update status kerja sama",
      "Catat creator yang perlu follow up",
    ],
  },
  {
    code: "RTPL-MNF05",
    title: "Cek Campaign Marketplace dan Iklan",
    category: "Monitoring",
    position_group: "MarketingNF",
    standard_result:
      "Marketing mengetahui promo marketplace dan iklan yang sedang berjalan tanpa mengambil alih pekerjaan Admin MP atau Ads Specialist.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "13:00",
    target_time_end: "14:30",
    sort_order: 5,
    checklist: [
      "Cek promo marketplace aktif",
      "Cek produk yang sedang diiklankan",
      "Cek stok produk campaign",
      "Cek voucher atau harga promo",
      "Cek laporan singkat advertising",
      "Catat ketidaksesuaian campaign",
      "Koordinasikan koreksi ke Admin MP atau Advertising",
    ],
  },
  {
    code: "RTPL-MNF06",
    title: "Cek Feedback Customer dan Materi Edukasi",
    category: "Monitoring",
    position_group: "MarketingNF",
    standard_result:
      "Pertanyaan, keberatan, komplain, dan kebutuhan customer digunakan sebagai bahan konten berikutnya.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "14:30",
    target_time_end: "16:00",
    sort_order: 6,
    checklist: [
      "Cek pertanyaan berulang dari CS",
      "Cek alasan customer tidak membeli",
      "Cek komplain produk",
      "Cek testimoni customer",
      "Catat ide konten edukasi",
      "Catat kebutuhan FAQ produk",
      "Kirim materi penting ke tim konten",
    ],
  },
  {
    code: "RTPL-MNF07",
    title: "Laporan Marketing NF Harian",
    category: "Closing",
    position_group: "MarketingNF",
    standard_result:
      "Progres konten, affiliate, campaign, stok prioritas, dan kendala NF tercatat.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "16:00",
    target_time_end: "17:00",
    sort_order: 7,
    checklist: [
      "Catat konten yang dibuat",
      "Catat konten yang tayang",
      "Catat progres affiliate",
      "Catat produk prioritas",
      "Catat campaign aktif",
      "Catat masukan CS",
      "Tulis prioritas besok",
      "Kirim laporan ke owner",
    ],
  },
];
