/** Seed definitions for Daily Activity SOP templates (ported from v1 PR #19). */
import type { ReportTemplateCategory, ReportTemplateKind } from "@nusafood/types";

export type DailyActivitySeedDef = {
  code: string;
  title: string;
  category: ReportTemplateCategory;
  position_group: string | null;
  outlet_code?: string | null;
  standard_result: string;
  requires_photo: boolean;
  is_required_daily: boolean;
  kind?: ReportTemplateKind;
  target_time_start?: string;
  target_time_end?: string;
  sort_order: number;
  checklist: string[];
};

export const DAILY_ACTIVITY_SEED_TEMPLATES: DailyActivitySeedDef[] = [

  // —— Waiters (5) ——
  {
    code: "RTPL-W01",
    title: "Opening Area Customer",
    category: "Opening",
    position_group: "Waiters",
    standard_result:
      "Area customer siap buka: bersih, meja rapi, lampu/AC/musik OK, siap terima tamu.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "07:30",
    target_time_end: "08:30",
    sort_order: 1,
    checklist: [
      "Lantai area customer bersih / tidak becek",
      "Meja dan kursi rapi, tidak goyang",
      "Peralatan makan/serbet tersedia di stasiun",
      "Lampu dan AC menyala sesuai standar",
      "Musik / ambience aktif",
      "Pintu masuk dan area depan bersih",
      "Tidak ada sampah atau barang berserakan",
    ],
  },
  {
    code: "RTPL-W02",
    title: "Bersihin WC",
    category: "Cleaning",
    position_group: "Waiters",
    standard_result:
      "WC bersih, kering, tidak bau, sabun/tisu tersedia, sampah kosong, siap dipakai customer.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "09:00",
    target_time_end: "10:00",
    sort_order: 2,
    checklist: [
      "Lantai sudah disikat / dipel",
      "Closet bersih",
      "Wastafel bersih",
      "Kaca bersih",
      "Sampah sudah dibuang",
      "Sabun tersedia",
      "Tisu tersedia",
      "Tidak bau",
      "Lantai tidak becek / tidak ada genangan air",
    ],
  },
  {
    code: "RTPL-W03",
    title: "Cek Meja dan Kursi",
    category: "Cleaning",
    position_group: "Waiters",
    standard_result: "Semua meja/kursi bersih, stabil, siap pakai customer.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "11:00",
    sort_order: 3,
    checklist: [
      "Permukaan meja bersih (tidak lengket)",
      "Kursi bersih dan tidak goyang",
      "Tidak ada sisa makanan / noda",
      "Layout meja rapi sesuai standar",
      "Condiment / tissue meja lengkap",
    ],
  },
  {
    code: "RTPL-W04",
    title: "Cek Tanaman",
    category: "Maintenance",
    position_group: "Waiters",
    standard_result: "Tanaman hijau, pot bersih, tidak layu / kering.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "11:00",
    target_time_end: "12:00",
    sort_order: 4,
    checklist: [
      "Daun tidak layu / kuning berlebih",
      "Tanah cukup lembab (disiram jika perlu)",
      "Pot dan area sekitar bersih dari sampah daun",
      "Tanaman tidak menghalangi jalan customer",
    ],
  },
  {
    code: "RTPL-W05",
    title: "Closing Area Customer",
    category: "Closing",
    position_group: "Waiters",
    standard_result: "Area customer bersih, sampah dibuang, siap buka esok hari.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "21:00",
    target_time_end: "22:00",
    sort_order: 5,
    checklist: [
      "Semua meja dibersihkan",
      "Kursi dirapikan",
      "Lantai dipel / disapu",
      "Sampah area customer dibuang",
      "Lampu / AC dimatikan sesuai SOP",
      "Pintu / area aman",
    ],
  },
  // —— Bar (5) ——
  {
    code: "RTPL-B01",
    title: "Opening Bar",
    category: "Opening",
    position_group: "Bar",
    standard_result: "Bar siap operasional: mesin OK, area bersih, stok awal cukup.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "07:30",
    target_time_end: "08:30",
    sort_order: 1,
    checklist: [
      "Area bar bersih dan rapi",
      "Mesin espresso menyala / siap",
      "Grinder dicek dan siap",
      "Steam wand bersih",
      "Stok susu / sirup cukup untuk opening",
      "Cup, lid, sedotan tersedia di stasiun",
    ],
  },
  {
    code: "RTPL-B02",
    title: "Cek Stok Cup / Sedotan",
    category: "Stock",
    position_group: "Bar",
    standard_result: "Stok cup, lid, sedotan cukup untuk operasional hari ini.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "09:00",
    target_time_end: "10:00",
    sort_order: 2,
    checklist: [
      "Cup hot cukup",
      "Cup cold cukup",
      "Lid tersedia",
      "Sedotan tersedia",
      "Tissue / napkin stasiun cukup",
      "Catat item yang hampir habis",
    ],
  },
  {
    code: "RTPL-B03",
    title: "Cek Mesin dan Grinder",
    category: "Maintenance",
    position_group: "Bar",
    standard_result: "Mesin dan grinder berfungsi normal, tidak ada kebocoran / bunyi aneh.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "11:00",
    sort_order: 3,
    checklist: [
      "Tekanan mesin normal",
      "Grinder mengeluarkan bubuk konsisten",
      "Tidak ada kebocoran air / uap",
      "Drip tray bersih",
      "Group head bersih",
    ],
  },
  {
    code: "RTPL-B04",
    title: "Bersihin Bar",
    category: "Cleaning",
    position_group: "Bar",
    standard_result: "Area bar bersih, counter kering, alat dicuci / disimpan rapi.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "14:00",
    target_time_end: "15:00",
    sort_order: 4,
    checklist: [
      "Counter bar dibersihkan",
      "Alat shaker / spoon dicuci",
      "Spill mat / drip tray bersih",
      "Lantai area bar tidak lengket",
      "Sampah bar dibuang",
    ],
  },
  {
    code: "RTPL-B05",
    title: "Closing Bar",
    category: "Closing",
    position_group: "Bar",
    standard_result: "Bar ditutup sesuai SOP: bersih, mesin off, stok diamankan.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "21:00",
    target_time_end: "22:00",
    sort_order: 5,
    checklist: [
      "Backflush / bilas mesin sesuai SOP",
      "Grinder dimatikan / dibersihkan",
      "Susu dan bahan perishable disimpan",
      "Area bar bersih dan kering",
      "Listrik / gas non-esensial dimatikan",
      "Sampah dibuang",
    ],
  },
  // —— Dapur (5) ——
  {
    code: "RTPL-D01",
    title: "Opening Dapur",
    category: "Opening",
    position_group: "Dapur",
    standard_result: "Dapur siap produksi: bersih, peralatan siap, suhu cold storage OK.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "07:00",
    target_time_end: "08:00",
    sort_order: 1,
    checklist: [
      "Area dapur bersih sebelum mulai",
      "Peralatan utama siap pakai",
      "Kompor / oven dicek",
      "Chiller / freezer suhu normal",
      "Bahan opening tersedia di stasiun",
      "Tangan / apron / kebersihan personal OK",
    ],
  },
  {
    code: "RTPL-D02",
    title: "Cek Bahan Siap Jual",
    category: "Stock",
    position_group: "Dapur",
    standard_result: "Bahan siap jual cukup, layak, tidak expired / busuk.",
    requires_photo: false,
    is_required_daily: true,
    target_time_start: "08:00",
    target_time_end: "09:00",
    sort_order: 2,
    checklist: [
      "Stok menu utama cukup untuk service",
      "Tidak ada bahan busuk / bau tidak wajar",
      "Label tanggal / FIFO dipatuhi",
      "Item hampir habis dicatat",
      "Bumbu / sauce stasiun lengkap",
    ],
  },
  {
    code: "RTPL-D03",
    title: "Produksi Bahan Harian",
    category: "Production",
    position_group: "Dapur",
    standard_result: "Produksi harian selesai sesuai target, disimpan dengan benar.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "09:00",
    target_time_end: "11:00",
    sort_order: 3,
    checklist: [
      "Produksi sesuai daftar harian",
      "Porsi / takaran sesuai resep",
      "Hasil disimpan di wadah bersih berlabel",
      "Suhu penyimpanan sesuai standar",
      "Area produksi dibersihkan setelah selesai",
    ],
  },
  {
    code: "RTPL-D04",
    title: "Cek Chiller / Freezer",
    category: "Maintenance",
    position_group: "Dapur",
    standard_result: "Chiller & freezer dingin sesuai standar, rapi, tidak bau.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "12:00",
    target_time_end: "13:00",
    sort_order: 4,
    checklist: [
      "Suhu chiller dalam rentang aman",
      "Suhu freezer dalam rentang aman",
      "Pintu menutup rapat",
      "Tidak ada bau busuk",
      "Barang tersusun rapi / tidak overfill",
      "Tidak ada kebocoran / es berlebih abnormal",
    ],
  },
  {
    code: "RTPL-D05",
    title: "Closing Dapur",
    category: "Closing",
    position_group: "Dapur",
    standard_result: "Dapur bersih, sampah dibuang, api/listrik aman, siap esok hari.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "21:00",
    target_time_end: "22:00",
    sort_order: 5,
    checklist: [
      "Peralatan dicuci dan disimpan",
      "Kompor / oven dimatikan",
      "Area dapur dipel / disapu",
      "Sampah dapur dibuang",
      "Bahan disimpan kembali ke cold storage",
      "Listrik non-esensial dimatikan",
    ],
  },
  // —— PA / OB / Public Area — Kopi Buri Umah (KBU) ——
  {
    code: "RTPL-PA01",
    title: "Opening Public Area Customer",
    category: "Opening",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Area customer siap buka, bersih, kering, tidak bau, tidak ada sampah kecil, meja kursi rapi, lantai aman diinjak, dan semua titik terlihat layak untuk tamu.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "08:30",
    target_time_end: "10:00",
    sort_order: 1,
    checklist: [
      "Area depan outlet disapu bersih dari debu, daun, puntung rokok, plastik, tisu, dan sampah kecil",
      "Area masuk / pintu / jalur customer bersih dan tidak licin",
      "Meja customer dilap bersih, tidak lengket, tidak ada noda makanan/minuman",
      "Kursi customer dirapikan sesuai posisi standar",
      "Lantai area makan disapu dan dipel, tidak ada bekas minyak, tanah, atau remah",
      "Kolong meja dicek, tidak ada sampah tersembunyi",
      "Tempat sampah customer dikosongkan jika penuh, plastik diganti bila kotor/bau",
      "Area tunggu / lobby / sekitar kasir luar bersih dan rapi",
      "Kaca / pintu / area terlihat depan dilap jika ada bekas tangan atau noda",
      "Foto laporan menampilkan area luas (bukan close-up satu titik saja)",
    ],
  },
  {
    code: "RTPL-PA02",
    title: "Toilet Customer Check",
    category: "Cleaning",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Toilet bersih, tidak bau pesing, lantai kering/aman, kloset bersih, wastafel bersih, sabun/tisu tersedia, dan tidak ada sampah menumpuk.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "09:00",
    target_time_end: "10:00",
    sort_order: 2,
    checklist: [
      "Kloset disikat bersih bagian dalam, dudukan, pinggir, dan area belakang",
      "Lantai toilet disikat/pel, tidak licin, tidak ada rambut, tisu, atau noda kuning",
      "Wastafel dibersihkan dari noda air, sisa sabun, rambut, dan kerak",
      "Kaca toilet dilap, tidak buram dan tidak banyak bercak air",
      "Tempat sampah toilet dikosongkan dan plastik diganti bila kotor/bau",
      "Dinding sekitar kloset dicek, tidak ada cipratan atau noda",
      "Gayung/ember/alat toilet dirapikan dan bersih",
      "Sabun, tisu, atau kebutuhan toilet dicek (habis → tulis kendala)",
      "Bau toilet dicek (masih bau setelah dibersihkan → lapor)",
      "Foto menunjukkan kloset, lantai, wastafel, dan tempat sampah",
    ],
  },
  {
    code: "RTPL-PA03",
    title: "Area Makan Customer Check",
    category: "Cleaning",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Area makan customer selalu siap dipakai, meja tidak lengket, kursi rapi, lantai bersih, tidak ada sampah, dan area nyaman untuk tamu.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "12:00",
    sort_order: 3,
    checklist: [
      "Meja yang sudah dipakai langsung dibersihkan",
      "Sisa piring/gelas kotor dibantu angkat ke area cuci sesuai arahan",
      "Permukaan meja dilap sampai tidak berminyak/lengket",
      "Kursi dikembalikan ke posisi rapi",
      "Lantai sekitar meja disapu dari remah, nasi, tulang, tisu, plastik, dan sampah kecil",
      "Kolong meja dicek setelah customer pergi",
      "Tissue, saus, sendok, atau perlengkapan meja dicek jika area tersebut pakai",
      "Area tidak dibiarkan kotor lebih dari 5 menit setelah customer pergi",
      "Jika area ramai dan belum sempat bersih, wajib tulis kendala (bukan diam)",
      "Foto menampilkan area yang sudah dirapikan (bukan sebelum kerja)",
    ],
  },
  {
    code: "RTPL-PA04",
    title: "Halaman & Parkiran Check",
    category: "Cleaning",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Area depan terlihat bersih dari jalan, tidak ada sampah kecil, tidak ada daun menumpuk, parkiran rapi, dan kesan pertama customer bagus.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "11:30",
    sort_order: 4,
    checklist: [
      "Area parkir disapu dari daun, plastik, puntung rokok, botol, tisu, dan sampah kecil",
      "Jalur masuk customer bersih dan tidak mengganggu akses",
      "Pot tanaman / area tanaman dicek, tidak ada sampah di dalam pot",
      "Tanaman disiram sesuai kebutuhan (terutama pagi/sore saat panas)",
      "Rumput kecil/liar yang terlihat mengganggu dicabut",
      "Area depan signage / pagar / jalan masuk dirapikan",
      "Genangan air, tanah becek, atau area licin wajib dilaporkan",
      "Tempat sampah outdoor dicek, tidak boleh penuh sampai meluber",
      "Rokok/puntung di area depan wajib dibersihkan",
      "Foto menampilkan area depan secara luas",
    ],
  },
  {
    code: "RTPL-PA05",
    title: "Taman, Tanaman & Rumput Kecil",
    category: "Maintenance",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Tanaman terlihat hidup dan rapi, tidak kering karena lupa disiram, pot bersih dari sampah, dan rumput liar kecil tidak dibiarkan tumbuh berantakan.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "15:00",
    target_time_end: "16:00",
    sort_order: 5,
    checklist: [
      "Semua tanaman area customer dicek satu per satu",
      "Tanaman disiram sesuai kondisi cuaca",
      "Daun kering yang jatuh dibersihkan",
      "Pot tanaman dibersihkan dari plastik, puntung rokok, tisu, atau sampah kecil",
      "Rumput kecil/liar di jalur customer dicabut",
      "Area sekitar tanaman disapu setelah disiram jika kotor",
      "Tanaman rusak/kering difoto dan dilaporkan",
      "Selang/alat siram dikembalikan ke tempatnya",
      "Tidak hanya foto tanaman tanpa benar-benar disiram",
      "Foto menunjukkan tanaman/area setelah rapi",
    ],
  },
  {
    code: "RTPL-PA06",
    title: "Sampah & Tempat Sampah Check",
    category: "Cleaning",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Tempat sampah tidak penuh, tidak bau, tidak meluber, plastik sampah rapi, dan area sekitar tempat sampah bersih.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "11:00",
    target_time_end: "12:00",
    sort_order: 6,
    checklist: [
      "Semua tempat sampah customer dicek",
      "Tempat sampah toilet dicek",
      "Tempat sampah outdoor dicek",
      "Sampah yang penuh segera dibuang ke titik pembuangan",
      "Plastik sampah diganti jika kotor, basah, atau bau",
      "Area sekitar tempat sampah disapu/pel jika ada tumpahan",
      "Tutup tempat sampah dibersihkan jika kotor",
      "Sampah kardus/botol/plastik besar dipisahkan jika mengganggu area",
      "Jika sampah belum bisa dibuang karena kendala, wajib tulis alasan jelas",
      "Foto menunjukkan tempat sampah setelah dibersihkan",
    ],
  },
  {
    code: "RTPL-PA07",
    title: "Mushola / Area Ibadah Check",
    category: "Cleaning",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Area ibadah bersih, tidak bau, alat ibadah rapi, lantai bersih, dan layak digunakan customer/staff.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "10:00",
    target_time_end: "11:00",
    sort_order: 7,
    checklist: [
      "Lantai mushola disapu dan dipel",
      "Sajadah/mukena/sarung dirapikan",
      "Area wudhu dicek, tidak licin dan tidak bau",
      "Sampah kecil dibersihkan",
      "Rak/perlengkapan ibadah dirapikan",
      "Kipas/lampu dicek menyala normal jika digunakan",
      "Bau lembap wajib dilaporkan",
      "Alat ibadah kotor wajib dipisahkan/lapor",
      "Tidak ada barang pribadi berantakan",
      "Foto area rapi setelah selesai",
    ],
  },
  {
    code: "RTPL-PA08",
    title: "Closing Public Area Customer",
    category: "Closing",
    position_group: "PA",
    outlet_code: "KBU",
    standard_result:
      "Area customer ditutup dalam kondisi bersih, sampah aman, toilet bersih, meja kursi rapi, lantai tidak meninggalkan kotoran untuk shift besok.",
    requires_photo: true,
    is_required_daily: true,
    target_time_start: "21:00",
    target_time_end: "22:00",
    sort_order: 8,
    checklist: [
      "Semua meja customer dibersihkan",
      "Semua kursi dirapikan",
      "Lantai area makan disapu dan dipel titik kotor",
      "Kolong meja dicek ulang",
      "Toilet dicek ulang sebelum tutup",
      "Tempat sampah dicek dan dibuang jika penuh/bau",
      "Area depan dicek dari sampah malam (puntung rokok, plastik, tisu)",
      "Peralatan kebersihan dicuci/rendam/dirapikan sesuai tempat",
      "Kendala closing wajib ditulis jelas",
      "Foto menunjukkan kondisi akhir area setelah tutup",
    ],
  },
  // —— Quick kendala (semua posisi) ——
  {
    code: "RTPL-K01",
    title: "Lapor Kendala Operasional",
    category: "Kendala",
    position_group: null,
    outlet_code: null,
    standard_result: "Kendala tercatat jelas agar leader bisa follow up.",
    requires_photo: false,
    is_required_daily: false,
    kind: "issue_quick",
    sort_order: 99,
    checklist: [
      "Jenis kendala sudah dipilih di status kondisi",
      "Lokasi / area kendala sudah jelas di catatan",
      "Foto diambil jika relevan (opsional)",
    ],
  },
];
